# Site settings
title: Learn, Code, and Draw it Out
header-img: img/home-bg.3.png
email: richardburdx@yahoo.com
copyright_name: Richard Burd
description: > # this means to ignore newlines until "baseurl:"
  Making Sense of a World Written in Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Richard-Burd
learn_profile: Richard-Burd
email_username: richardburdx@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
