# Site settings
title: Learn, Code, and Draw it Out
header-img: img/banners/software.png
email: rick.a.burd@gmail.com
copyright_name: Richard Burd
description: > # this means to ignore newlines until "baseurl:"
  A blog that takes white boarding to the next level
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  Richard-Burd
learn_profile: Richard-Burd
email_username: richardburdx@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

# https://jekyllrb.com/docs/pagination/
# paginate_path: "/blog/page:num/"
paginate_path: "/blog/page:num/"


exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# This video was used as a reference:
# https://www.youtube.com/watch?v=mGMlLSM0HQM
# This section will subdivide the portfolio section into subsections:
#   1.) Technical Writing & Illustration Portfolio
#   2.) Software Design Portfolio (with wireframes and URL links)
#   3.) Hardware/ Drone & Architecture Design portfolio
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
